# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MentorsHakaton' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MentorsHakaton

  pod 'Kingfisher', ' ~> 7.0'
  pod 'SwiftKeychainWrapper', '~> 4.0'
  pod 'AnyFormatKit', '~> 2.5.2'
  pod 'Cosmos', '~> 23.0'
  pod 'TinyConstraints'
end
