# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'MentorsHakaton' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MentorsHakaton

  pod 'Kingfisher', '~> 7.6.2'
  pod 'SwiftKeychainWrapper', '~> 4.0'
  pod 'AnyFormatKit', '~> 2.5.2'
  pod 'Cosmos', '~> 23.0'
  pod 'TinyConstraints'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end